const state={page:'dashboard',products:[],customers:[],suppliers:[]};
const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('en-PK',{minimumFractionDigits:2,maximumFractionDigits:2});
function toast(msg){const x=$('#toast');x.textContent=msg;x.classList.remove('hidden');setTimeout(()=>x.classList.add('hidden'),3000)}
const API_URL="https://script.google.com/macros/s/AKfycbyi8CaMtMxV7Prf5Dexoy03ao8v2XApxbw2rLK2hTlvYS_j9vV3Y7JbW-GrAS3XYUvAtA/exec";
const API_ACTIONS={apiDashboard:'dashboard',apiProducts:'products',apiCustomers:'customers',apiSuppliers:'suppliers',apiStock:'stock',apiLedger:'ledger',apiSale:'sale',apiPurchase:'purchase',apiPayment:'payment',apiExpense:'expense'};
function call(name,...args){
  const action=API_ACTIONS[name]||name;
  const payload=args.length===1 && args[0] && typeof args[0]==='object' ? args[0] : {};
  return new Promise((resolve,reject)=>{
    const cb='erp_cb_'+Date.now()+'_'+Math.floor(Math.random()*100000);
    const script=document.createElement('script');
    const cleanup=()=>{try{delete window[cb]}catch(e){};script.remove()};
    const timer=setTimeout(()=>{cleanup();reject(new Error('ERP server timeout'))},30000);
    window[cb]=function(response){
      clearTimeout(timer);cleanup();
      if(!response || response.ok===false) reject(new Error(response&&response.error||'ERP API error'));
      else resolve(response.data);
    };
    const params=new URLSearchParams();
    params.set('action',action);
    params.set('callback',cb);
    if(args.length===1 && payload && Object.keys(payload).length) params.set('payload',JSON.stringify(payload));
    script.src=API_URL+'?'+params.toString();
    script.onerror=()=>{clearTimeout(timer);cleanup();reject(new Error('Could not connect to ERP backend'))};
    document.head.appendChild(script);
  });
}
async function load(){ $('#content').innerHTML='<div class="loading">Loading...</div>'; try{switch(state.page){case'dashboard':return dashboard();case'products':return products();case'stock':return stock();case'customers':return customers();case'suppliers':return suppliers();case'ledger':return ledger();case'sales':return salesPage();case'purchases':return purchasesPage();case'payments':return paymentsPage();case'expenses':return expensesPage();}}catch(e){$('#content').innerHTML='<div class="panel danger">Error: '+esc(e.message||e)+'</div>'}}
async function dashboard(){const d=await call('apiDashboard');$('#content').innerHTML=`<div class="content"><div class="grid cards">${[['Products',d.productCount],['Customers',d.customerCount],['Suppliers',d.supplierCount],['Stock Qty',money(d.stockQty)],['Stock Value',money(d.stockValue)],['Low Stock',d.lowStockCount],['Sales',money(d.salesTotal)],['Purchases',money(d.purchasesTotal)]].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join('')}</div><div class="panel"><h2>Quick Actions</h2><div class="toolbar"><button class="btn primary" onclick="setPage('sales')">New Sale</button><button class="btn primary" onclick="setPage('purchases')">New Purchase</button><button class="btn secondary" onclick="setPage('payments')">Payment</button><button class="btn secondary" onclick="setPage('expenses')">Expense</button></div></div></div>`}
async function products(){state.products=await call('apiProducts');renderProductTable(state.products)}
function renderProductTable(rows){$('#content').innerHTML=`<div class="content"><div class="panel"><div class="panel-head"><h2>Products (${rows.length})</h2><input id="search" class="search" placeholder="Search..." oninput="filterProducts()"></div><div class="table-wrap"><table class="table"><thead><tr><th>Code</th><th>Description</th><th>Brand</th><th>Category</th><th>Unit</th><th>Stock</th><th>Purchase</th><th>Sale</th></tr></thead><tbody id="productRows"></tbody></table></div></div></div>`;drawProducts(rows)}
function filterProducts(){const q=$('#search').value.toLowerCase();drawProducts(state.products.filter(p=>Object.values(p).join(' ').toLowerCase().includes(q)))}
function drawProducts(rows){$('#productRows').innerHTML=rows.slice(0,500).map(p=>`<tr><td><b>${esc(p.Code||p.ProductID)}</b></td><td>${esc(p.Description)}</td><td>${esc(p.Brand)}</td><td>${esc(p.Category)}</td><td>${esc(p.Unit)}</td><td>${esc(p.CurrentStock)}</td><td>${money(p.PurchasePrice)}</td><td>${money(p.SalePrice)}</td></tr>`).join('')}
async function stock(){state.products=await call('apiProducts');$('#content').innerHTML=`<div class="content"><div class="panel"><div class="panel-head"><h2>Current Stock</h2><input id="search" class="search" placeholder="Search..." oninput="filterStock()"></div><div class="table-wrap"><table class="table"><thead><tr><th>Code</th><th>Description</th><th>Brand</th><th>Stock</th><th>Min</th><th>Cost</th><th>Value</th></tr></thead><tbody id="stockRows"></tbody></table></div></div></div>`;drawStock(state.products)}
function filterStock(){const q=$('#search').value.toLowerCase();drawStock(state.products.filter(p=>Object.values(p).join(' ').toLowerCase().includes(q)))}
function drawStock(rows){$('#stockRows').innerHTML=rows.map(p=>{const q=Number(p.CurrentStock)||0,c=Number(p.PurchasePrice)||0;return `<tr><td>${esc(p.Code||p.ProductID)}</td><td>${esc(p.Description)}</td><td>${esc(p.Brand)}</td><td>${money(q)}</td><td>${money(p.MinStock)}</td><td>${money(c)}</td><td>${money(q*c)}</td></tr>`}).join('')}
async function customers(){state.customers=await call('apiCustomers');renderParties('Customers',state.customers,['CustomerID','Name','Phone','WhatsApp','CreditLimit','ClosingBalance'])}
async function suppliers(){state.suppliers=await call('apiSuppliers');renderParties('Suppliers',state.suppliers,['SupplierID','Name','Phone','Email','ClosingBalance'])}
function renderParties(title,rows,cols){$('#content').innerHTML=`<div class="content"><div class="panel"><div class="panel-head"><h2>${title} (${rows.length})</h2><input id="search" class="search" placeholder="Search..." oninput="filterParty()"></div><div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody id="partyRows"></tbody></table></div></div></div>`;drawParty(rows,cols)}
function filterParty(){const src=state.page==='customers'?state.customers:state.suppliers,q=$('#search').value.toLowerCase();const rows=src.filter(x=>Object.values(x).join(' ').toLowerCase().includes(q));const cols=state.page==='customers'?['CustomerID','Name','Phone','WhatsApp','CreditLimit','ClosingBalance']:['SupplierID','Name','Phone','Email','ClosingBalance'];drawParty(rows,cols)}
function drawParty(rows,cols){$('#partyRows').innerHTML=rows.slice(0,500).map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c])}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="10">No records</td></tr>'}
async function ledger(){const c=state.customers.length?state.customers:await call('apiCustomers'),s=state.suppliers.length?state.suppliers:await call('apiSuppliers'),all=[...c.map(x=>({...x,_type:'customer',_id:x.CustomerID})),...s.map(x=>({...x,_type:'supplier',_id:x.SupplierID}))];$('#content').innerHTML=`<div class="content"><div class="panel"><h2>Party Ledger</h2><div class="toolbar"><select id="party" class="search"><option value="">Select account</option>${all.map(x=>`<option value="${x._type}|${x._id}">${esc(x.Name)} — ${x._type}</option>`).join('')}</select><button class="btn primary" onclick="loadLedger()">Open</button></div><div id="ledgerBox"></div></div></div>`}
async function loadLedger(){const v=$('#party').value;if(!v)return toast('Select an account');const [t,id]=v.split('|'),rows=await call('apiLedger',t,id);$('#ledgerBox').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Particular</th><th>Ref</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.Date)}</td><td>${esc(r.Particular)}</td><td>${esc(r.Ref)}</td><td>${money(r.Debit)}</td><td>${money(r.Credit)}</td><td>${money(r.Balance)}</td></tr>`).join('')}</tbody></table></div>`}
function partyOptions(type){const a=type==='customer'?state.customers:state.suppliers;return a.map(x=>`<option value="${x[type==='customer'?'CustomerID':'SupplierID']}">${esc(x.Name)}</option>`).join('')}
async function ensureMasters(){if(!state.products.length)state.products=await call('apiProducts');if(!state.customers.length)state.customers=await call('apiCustomers');if(!state.suppliers.length)state.suppliers=await call('apiSuppliers')}
async function salesPage(){await ensureMasters();$('#content').innerHTML=txForm('sale')}
async function purchasesPage(){await ensureMasters();$('#content').innerHTML=txForm('purchase')}
function txForm(type){const sale=type==='sale', title=sale?'New Sale':'New Purchase';return `<div class="content"><div class="panel"><div class="panel-head"><h2>${title}</h2><input id="txDate" class="search" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="toolbar"><select id="partyId" class="search"><option value="">Select ${sale?'customer':'supplier'}</option>${partyOptions(sale?'customer':'supplier')}</select><input id="refNo" class="search" placeholder="${sale?'Invoice No (optional)':'Reference No'}"><input id="txDiscount" class="search" type="number" step="0.01" placeholder="Discount"></div><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Qty</th><th>${sale?'Sale Price':'Unit Cost'}</th><th>Discount</th><th></th></tr></thead><tbody id="txItems"></tbody></table></div><div class="toolbar"><button class="btn secondary" onclick="addTxRow('${type}')">+ Add Item</button><input id="txPaid" class="search" type="number" step="0.01" placeholder="Paid"><select id="payMethod" class="search"><option>cash</option><option>bank</option><option>cheque</option><option>online</option></select><button class="btn primary" onclick="submitTx('${type}')">Post ${sale?'Sale':'Purchase'}</button></div><div id="txTotal" class="panel-head"></div></div></div>`}
function addTxRow(type){const i=document.createElement('tr');i.innerHTML=`<td><select class="search tx-product"><option value="">Select product</option>${state.products.map(p=>`<option value="${p.ProductID}" data-sale="${Number(p.SalePrice)||0}" data-cost="${Number(p.PurchasePrice)||0}">${esc(p.Code||p.ProductID)} — ${esc(p.Description)}</option>`).join('')}</select></td><td><input class="search tx-qty" type="number" min="0.01" step="0.01" value="1"></td><td><input class="search tx-price" type="number" step="0.01" value="0"></td><td><input class="search tx-disc" type="number" step="0.01" value="0"></td><td><button class="btn secondary" onclick="this.closest('tr').remove();calcTx()">×</button></td>`;$('#txItems').appendChild(i);i.querySelector('.tx-product').onchange=()=>{const o=i.querySelector('.tx-product').selectedOptions[0];i.querySelector('.tx-price').value=type==='sale'?o.dataset.sale:o.dataset.cost;calcTx()};i.querySelectorAll('input').forEach(x=>x.oninput=calcTx);calcTx()}
function calcTx(){let n=0;document.querySelectorAll('#txItems tr').forEach(r=>{n+=(Number(r.querySelector('.tx-qty').value)||0)*(Number(r.querySelector('.tx-price').value)||0)-(Number(r.querySelector('.tx-disc').value)||0)});n-=Number($('#txDiscount')?.value)||0;if($('#txTotal'))$('#txTotal').innerHTML='<b>Net Total: '+money(Math.max(0,n))+'</b>'}
async function submitTx(type){try{const sale=type==='sale',items=[...document.querySelectorAll('#txItems tr')].map(r=>({productId:r.querySelector('.tx-product').value,qty:r.querySelector('.tx-qty').value,...(sale?{unitPrice:r.querySelector('.tx-price').value}:{unitCost:r.querySelector('.tx-price').value}),discount:r.querySelector('.tx-disc').value})).filter(x=>x.productId);if(!items.length)return toast('Add at least one item');const p={date:$('#txDate').value,[sale?'customerId':'supplierId']:$('#partyId').value,invoiceNo:sale?$('#refNo').value:'',referenceNo:sale?'':$('#refNo').value,discount:$('#txDiscount').value,paid:$('#txPaid').value,paymentMethod:$('#payMethod').value,items};if(!p[sale?'customerId':'supplierId'])return toast('Select party');const r=await call(sale?'apiSale':'apiPurchase',p);toast((sale?'Sale':'Purchase')+' posted: '+(r.invoiceNo||r.purchaseId));setPage(sale?'sales':'purchases')}catch(e){toast(e.message||e)}}
async function paymentsPage(){await ensureMasters();$('#content').innerHTML=`<div class="content"><div class="panel"><h2>Party Payment</h2><div class="toolbar"><select id="payType" class="search" onchange="renderPayParty()"><option value="customer">Customer Receipt</option><option value="supplier">Supplier Payment</option></select><select id="payParty" class="search"></select><input id="payAmount" class="search" type="number" step="0.01" placeholder="Amount"><select id="payMethod2" class="search"><option>cash</option><option>bank</option><option>cheque</option><option>online</option></select><input id="payRef" class="search" placeholder="Reference"><button class="btn primary" onclick="submitPayment()">Post Payment</button></div></div></div>`;renderPayParty()}
function renderPayParty(){const t=$('#payType').value,a=t==='customer'?state.customers:state.suppliers;$('#payParty').innerHTML=a.map(x=>`<option value="${x[t==='customer'?'CustomerID':'SupplierID']}">${esc(x.Name)}</option>`).join('')}
async function submitPayment(){try{const t=$('#payType').value;const r=await call('apiPayment',{partyType:t,partyId:$('#payParty').value,amount:$('#payAmount').value,direction:t==='customer'?'in':'out',method:$('#payMethod2').value,reference:$('#payRef').value});toast('Payment posted: '+r.paymentId);load()}catch(e){toast(e.message||e)}}
async function expensesPage(){$('#content').innerHTML=`<div class="content"><div class="panel"><h2>New Expense</h2><div class="toolbar"><input id="exDate" class="search" type="date" value="${new Date().toISOString().slice(0,10)}"><input id="exCat" class="search" placeholder="Category"><input id="exDesc" class="search" placeholder="Description"><input id="exAmount" class="search" type="number" step="0.01" placeholder="Amount"><select id="exMethod" class="search"><option>cash</option><option>bank</option><option>cheque</option><option>online</option></select><button class="btn primary" onclick="submitExpense()">Post Expense</button></div></div></div>`}
async function submitExpense(){try{const r=await call('apiExpense',{date:$('#exDate').value,category:$('#exCat').value,description:$('#exDesc').value,amount:$('#exAmount').value,paymentMethod:$('#exMethod').value});toast('Expense posted: '+r.expenseId);load()}catch(e){toast(e.message||e)}}
async function sales(){await salesPage()} async function purchases(){await purchasesPage()}
function setPage(p){state.page=p;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#pageTitle').textContent=p.charAt(0).toUpperCase()+p.slice(1);$('#crumb').textContent=$('#pageTitle').textContent;load()}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setPage(b.dataset.page));$('#refreshBtn').onclick=load;load()});